// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace tryServer {
    
    
    public partial class MainWindow {
        
        private Gtk.Notebook notebook3;
        
        private Gtk.Fixed fixed3;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.Button btnStart;
        
        private Gtk.Button btnStop;
        
        private Gtk.Button btnSettings;
        
        private Gtk.Label label7;
        
        private Gtk.Image imgOffline;
        
        private Gtk.Image imgOnline;
        
        private Gtk.Label label6;
        
        private Gtk.ComboBox cmbInstance;
        
        private Gtk.Label label4;
        
        private Gtk.Fixed fixed4;
        
        private Gtk.Label label10;
        
        private Gtk.Label label11;
        
        private Gtk.Label label12;
        
        private Gtk.Label label13;
        
        private Gtk.Label label14;
        
        private Gtk.CheckButton chkStart;
        
        private Gtk.Button button4;
        
        private Gtk.Button button5;
        
        private Gtk.Entry entry1;
        
        private Gtk.Entry entry2;
        
        private Gtk.Entry entry4;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Entry entry5;
        
        private Gtk.Entry entry6;
        
        private Gtk.HSeparator hseparator4;
        
        private Gtk.HSeparator hseparator5;
        
        private Gtk.TreeView treeview1;
        
        private Gtk.Label label5;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget tryServer.MainWindow
            this.WidthRequest = 380;
            this.HeightRequest = 330;
            this.CanFocus = true;
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "tryServer.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("Main");
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            this.Resizable = false;
            this.AllowGrow = false;
            this.DestroyWithParent = true;
            // Container child tryServer.MainWindow.Gtk.Container+ContainerChild
            this.notebook3 = new Gtk.Notebook();
            this.notebook3.WidthRequest = 300;
            this.notebook3.CanFocus = true;
            this.notebook3.Name = "notebook3";
            // Container child notebook3.Gtk.Notebook+NotebookChild
            this.fixed3 = new Gtk.Fixed();
            this.fixed3.Name = "fixed3";
            this.fixed3.HasWindow = false;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Stop server");
            this.fixed3.Add(this.label8);
            Gtk.Fixed.FixedChild w1 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.label8]));
            w1.X = 104;
            w1.Y = 172;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Connections Settings");
            this.fixed3.Add(this.label9);
            Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.label9]));
            w2.X = 104;
            w2.Y = 230;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.btnStart = new Gtk.Button();
            this.btnStart.WidthRequest = 80;
            this.btnStart.HeightRequest = 55;
            this.btnStart.CanFocus = true;
            this.btnStart.Name = "btnStart";
            this.btnStart.UseUnderline = true;
            // Container child btnStart.Gtk.Container+ContainerChild
            Gtk.Alignment w3 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            w3.Name = "GtkAlignment";
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w4 = new Gtk.HBox();
            w4.Name = "GtkHBox";
            w4.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w5 = new Gtk.Image();
            w5.Name = "image14";
            w5.Pixbuf = Gdk.Pixbuf.LoadFromResource("play.png");
            w4.Add(w5);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w7 = new Gtk.Label();
            w7.Name = "GtkLabel";
            w7.LabelProp = "";
            w4.Add(w7);
            w3.Add(w4);
            this.btnStart.Add(w3);
            this.fixed3.Add(this.btnStart);
            Gtk.Fixed.FixedChild w11 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.btnStart]));
            w11.X = 14;
            w11.Y = 99;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.btnStop = new Gtk.Button();
            this.btnStop.WidthRequest = 80;
            this.btnStop.HeightRequest = 55;
            this.btnStop.CanFocus = true;
            this.btnStop.Name = "btnStop";
            this.btnStop.UseUnderline = true;
            // Container child btnStop.Gtk.Container+ContainerChild
            Gtk.Alignment w12 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            w12.Name = "GtkAlignment1";
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            Gtk.HBox w13 = new Gtk.HBox();
            w13.Name = "GtkHBox1";
            w13.Spacing = 2;
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Image w14 = new Gtk.Image();
            w14.Name = "image15";
            w14.Pixbuf = Gdk.Pixbuf.LoadFromResource("process-stop.png");
            w13.Add(w14);
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Label w16 = new Gtk.Label();
            w16.Name = "GtkLabel1";
            w16.LabelProp = "";
            w13.Add(w16);
            w12.Add(w13);
            this.btnStop.Add(w12);
            this.fixed3.Add(this.btnStop);
            Gtk.Fixed.FixedChild w20 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.btnStop]));
            w20.X = 14;
            w20.Y = 157;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.btnSettings = new Gtk.Button();
            this.btnSettings.WidthRequest = 80;
            this.btnSettings.HeightRequest = 55;
            this.btnSettings.CanFocus = true;
            this.btnSettings.Name = "btnSettings";
            this.btnSettings.UseUnderline = true;
            // Container child btnSettings.Gtk.Container+ContainerChild
            Gtk.Alignment w21 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            w21.Name = "GtkAlignment2";
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            Gtk.HBox w22 = new Gtk.HBox();
            w22.Name = "GtkHBox2";
            w22.Spacing = 2;
            // Container child GtkHBox2.Gtk.Container+ContainerChild
            Gtk.Image w23 = new Gtk.Image();
            w23.Name = "image16";
            w23.Pixbuf = Gdk.Pixbuf.LoadFromResource("db_sql_.png");
            w22.Add(w23);
            // Container child GtkHBox2.Gtk.Container+ContainerChild
            Gtk.Label w25 = new Gtk.Label();
            w25.Name = "GtkLabel2";
            w25.LabelProp = "";
            w22.Add(w25);
            w21.Add(w22);
            this.btnSettings.Add(w21);
            this.fixed3.Add(this.btnSettings);
            Gtk.Fixed.FixedChild w29 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.btnSettings]));
            w29.X = 14;
            w29.Y = 215;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Start server");
            this.fixed3.Add(this.label7);
            Gtk.Fixed.FixedChild w30 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.label7]));
            w30.X = 104;
            w30.Y = 116;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.imgOffline = new Gtk.Image();
            this.imgOffline.Name = "imgOffline";
            this.imgOffline.Pixbuf = Gdk.Pixbuf.LoadFromResource("Internet - Offline.png");
            this.fixed3.Add(this.imgOffline);
            Gtk.Fixed.FixedChild w31 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.imgOffline]));
            w31.X = 211;
            w31.Y = 93;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.imgOnline = new Gtk.Image();
            this.imgOnline.Name = "imgOnline";
            this.imgOnline.Pixbuf = Gdk.Pixbuf.LoadFromResource("Network Configuration.png");
            this.fixed3.Add(this.imgOnline);
            Gtk.Fixed.FixedChild w32 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.imgOnline]));
            w32.X = 211;
            w32.Y = 93;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Instance");
            this.fixed3.Add(this.label6);
            Gtk.Fixed.FixedChild w33 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.label6]));
            w33.X = 16;
            w33.Y = 39;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.cmbInstance = Gtk.ComboBox.NewText();
            this.cmbInstance.WidthRequest = 250;
            this.cmbInstance.Name = "cmbInstance";
            this.fixed3.Add(this.cmbInstance);
            Gtk.Fixed.FixedChild w34 = ((Gtk.Fixed.FixedChild)(this.fixed3[this.cmbInstance]));
            w34.X = 93;
            w34.Y = 31;
            this.notebook3.Add(this.fixed3);
            // Notebook tab
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Settings");
            this.notebook3.SetTabLabel(this.fixed3, this.label4);
            // Container child notebook3.Gtk.Notebook+NotebookChild
            this.fixed4 = new Gtk.Fixed();
            this.fixed4.Name = "fixed4";
            this.fixed4.HasWindow = false;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("Server");
            this.fixed4.Add(this.label10);
            Gtk.Fixed.FixedChild w36 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.label10]));
            w36.X = 175;
            w36.Y = 30;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Port");
            this.fixed4.Add(this.label11);
            Gtk.Fixed.FixedChild w37 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.label11]));
            w37.X = 175;
            w37.Y = 65;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("File");
            this.fixed4.Add(this.label12);
            Gtk.Fixed.FixedChild w38 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.label12]));
            w38.X = 175;
            w38.Y = 100;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.LabelProp = Mono.Unix.Catalog.GetString("User");
            this.fixed4.Add(this.label13);
            Gtk.Fixed.FixedChild w39 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.label13]));
            w39.X = 175;
            w39.Y = 145;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.label14 = new Gtk.Label();
            this.label14.Name = "label14";
            this.label14.LabelProp = Mono.Unix.Catalog.GetString("Password");
            this.fixed4.Add(this.label14);
            Gtk.Fixed.FixedChild w40 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.label14]));
            w40.X = 175;
            w40.Y = 180;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.chkStart = new Gtk.CheckButton();
            this.chkStart.CanFocus = true;
            this.chkStart.Name = "chkStart";
            this.chkStart.Label = Mono.Unix.Catalog.GetString("Start automatically");
            this.chkStart.DrawIndicator = true;
            this.chkStart.UseUnderline = true;
            this.fixed4.Add(this.chkStart);
            Gtk.Fixed.FixedChild w41 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.chkStart]));
            w41.X = 191;
            w41.Y = 216;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.button4 = new Gtk.Button();
            this.button4.WidthRequest = 80;
            this.button4.CanFocus = true;
            this.button4.Name = "button4";
            this.button4.UseUnderline = true;
            this.button4.Label = Mono.Unix.Catalog.GetString("Ok");
            this.fixed4.Add(this.button4);
            Gtk.Fixed.FixedChild w42 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.button4]));
            w42.X = 204;
            w42.Y = 253;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.button5 = new Gtk.Button();
            this.button5.WidthRequest = 80;
            this.button5.CanFocus = true;
            this.button5.Name = "button5";
            this.button5.UseUnderline = true;
            this.button5.Label = Mono.Unix.Catalog.GetString("Cancel");
            this.fixed4.Add(this.button5);
            Gtk.Fixed.FixedChild w43 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.button5]));
            w43.X = 288;
            w43.Y = 253;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.entry1 = new Gtk.Entry();
            this.entry1.WidthRequest = 120;
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.IsEditable = true;
            this.entry1.InvisibleChar = '●';
            this.fixed4.Add(this.entry1);
            Gtk.Fixed.FixedChild w44 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.entry1]));
            w44.X = 250;
            w44.Y = 25;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.entry2 = new Gtk.Entry();
            this.entry2.WidthRequest = 120;
            this.entry2.CanFocus = true;
            this.entry2.Name = "entry2";
            this.entry2.IsEditable = true;
            this.entry2.InvisibleChar = '●';
            this.fixed4.Add(this.entry2);
            Gtk.Fixed.FixedChild w45 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.entry2]));
            w45.X = 250;
            w45.Y = 60;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.entry4 = new Gtk.Entry();
            this.entry4.WidthRequest = 120;
            this.entry4.CanFocus = true;
            this.entry4.Name = "entry4";
            this.entry4.IsEditable = true;
            this.entry4.InvisibleChar = '●';
            this.fixed4.Add(this.entry4);
            Gtk.Fixed.FixedChild w46 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.entry4]));
            w46.X = 250;
            w46.Y = 95;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.WidthRequest = 200;
            this.hseparator1.Name = "hseparator1";
            this.fixed4.Add(this.hseparator1);
            Gtk.Fixed.FixedChild w47 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.hseparator1]));
            w47.X = 169;
            w47.Y = 129;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.entry5 = new Gtk.Entry();
            this.entry5.WidthRequest = 120;
            this.entry5.CanFocus = true;
            this.entry5.Name = "entry5";
            this.entry5.IsEditable = true;
            this.entry5.Visibility = false;
            this.entry5.InvisibleChar = '●';
            this.fixed4.Add(this.entry5);
            Gtk.Fixed.FixedChild w48 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.entry5]));
            w48.X = 250;
            w48.Y = 175;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.entry6 = new Gtk.Entry();
            this.entry6.WidthRequest = 120;
            this.entry6.CanFocus = true;
            this.entry6.Name = "entry6";
            this.entry6.IsEditable = true;
            this.entry6.InvisibleChar = '●';
            this.fixed4.Add(this.entry6);
            Gtk.Fixed.FixedChild w49 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.entry6]));
            w49.X = 248;
            w49.Y = 140;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.hseparator4 = new Gtk.HSeparator();
            this.hseparator4.WidthRequest = 150;
            this.hseparator4.Name = "hseparator4";
            this.fixed4.Add(this.hseparator4);
            Gtk.Fixed.FixedChild w50 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.hseparator4]));
            w50.X = 11;
            w50.Y = 10;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.hseparator5 = new Gtk.HSeparator();
            this.hseparator5.WidthRequest = 150;
            this.hseparator5.Name = "hseparator5";
            this.fixed4.Add(this.hseparator5);
            Gtk.Fixed.FixedChild w51 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.hseparator5]));
            w51.X = 9;
            w51.Y = 282;
            // Container child fixed4.Gtk.Fixed+FixedChild
            this.treeview1 = new Gtk.TreeView();
            this.treeview1.WidthRequest = 150;
            this.treeview1.HeightRequest = 270;
            this.treeview1.CanFocus = true;
            this.treeview1.Name = "treeview1";
            this.treeview1.FixedHeightMode = true;
            this.treeview1.HeadersVisible = false;
            this.fixed4.Add(this.treeview1);
            Gtk.Fixed.FixedChild w52 = ((Gtk.Fixed.FixedChild)(this.fixed4[this.treeview1]));
            w52.X = 11;
            w52.Y = 11;
            this.notebook3.Add(this.fixed4);
            Gtk.Notebook.NotebookChild w53 = ((Gtk.Notebook.NotebookChild)(this.notebook3[this.fixed4]));
            w53.Position = 1;
            // Notebook tab
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Registered items");
            this.notebook3.SetTabLabel(this.fixed4, this.label5);
            this.Add(this.notebook3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 419;
            this.DefaultHeight = 379;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.btnStart.Clicked += new System.EventHandler(this.OnBtnStartClicked);
            this.btnStop.Clicked += new System.EventHandler(this.OnBtnStopClicked);
            this.btnSettings.Clicked += new System.EventHandler(this.OnBtnSettingsClicked);
        }
    }
}
