// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace tryServer {
    
    
    public partial class frmSettings {
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Image image52;
        
        private Gtk.Image image53;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Entry txtServer;
        
        private Gtk.Entry txtPort;
        
        private Gtk.Entry txtFile;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private Gtk.Entry txtUser;
        
        private Gtk.Entry txtPassword;
        
        private Gtk.Label label10;
        
        private Gtk.Button btnUsers;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Entry txtFileUsers;
        
        private Gtk.Label label9;
        
        private Gtk.Button Ok;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget tryServer.frmSettings
            this.WidthRequest = 380;
            this.HeightRequest = 450;
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "tryServer.frmSettings";
            this.Title = Mono.Unix.Catalog.GetString("Settings");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            this.HasSeparator = false;
            // Internal child tryServer.frmSettings.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.HeightRequest = 390;
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Server");
            this.fixed1.Add(this.label4);
            Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
            w2.X = 135;
            w2.Y = 40;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Port");
            this.fixed1.Add(this.label5);
            Gtk.Fixed.FixedChild w3 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
            w3.X = 135;
            w3.Y = 80;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("File");
            this.fixed1.Add(this.label6);
            Gtk.Fixed.FixedChild w4 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
            w4.X = 135;
            w4.Y = 120;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.image52 = new Gtk.Image();
            this.image52.Name = "image52";
            this.image52.Pixbuf = Gdk.Pixbuf.LoadFromResource("_database.png");
            this.fixed1.Add(this.image52);
            Gtk.Fixed.FixedChild w5 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.image52]));
            w5.X = 35;
            w5.Y = 58;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.image53 = new Gtk.Image();
            this.image53.Name = "image53";
            this.image53.Pixbuf = Gdk.Pixbuf.LoadFromResource("password.png");
            this.fixed1.Add(this.image53);
            Gtk.Fixed.FixedChild w6 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.image53]));
            w6.X = 35;
            w6.Y = 174;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.WidthRequest = 380;
            this.hseparator1.Name = "hseparator1";
            this.fixed1.Add(this.hseparator1);
            Gtk.Fixed.FixedChild w7 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator1]));
            w7.X = 12;
            w7.Y = 151;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.txtServer = new Gtk.Entry();
            this.txtServer.CanFocus = true;
            this.txtServer.Name = "txtServer";
            this.txtServer.IsEditable = true;
            this.txtServer.InvisibleChar = '●';
            this.fixed1.Add(this.txtServer);
            Gtk.Fixed.FixedChild w8 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.txtServer]));
            w8.X = 215;
            w8.Y = 35;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.txtPort = new Gtk.Entry();
            this.txtPort.CanFocus = true;
            this.txtPort.Name = "txtPort";
            this.txtPort.IsEditable = true;
            this.txtPort.InvisibleChar = '●';
            this.fixed1.Add(this.txtPort);
            Gtk.Fixed.FixedChild w9 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.txtPort]));
            w9.X = 215;
            w9.Y = 75;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.txtFile = new Gtk.Entry();
            this.txtFile.CanFocus = true;
            this.txtFile.Name = "txtFile";
            this.txtFile.IsEditable = true;
            this.txtFile.InvisibleChar = '●';
            this.fixed1.Add(this.txtFile);
            Gtk.Fixed.FixedChild w10 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.txtFile]));
            w10.X = 215;
            w10.Y = 115;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("User");
            this.fixed1.Add(this.label7);
            Gtk.Fixed.FixedChild w11 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
            w11.X = 135;
            w11.Y = 175;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Password");
            this.fixed1.Add(this.label8);
            Gtk.Fixed.FixedChild w12 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label8]));
            w12.X = 135;
            w12.Y = 220;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.txtUser = new Gtk.Entry();
            this.txtUser.CanFocus = true;
            this.txtUser.Name = "txtUser";
            this.txtUser.IsEditable = true;
            this.txtUser.InvisibleChar = '●';
            this.fixed1.Add(this.txtUser);
            Gtk.Fixed.FixedChild w13 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.txtUser]));
            w13.X = 215;
            w13.Y = 170;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.txtPassword = new Gtk.Entry();
            this.txtPassword.CanFocus = true;
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.IsEditable = true;
            this.txtPassword.Visibility = false;
            this.txtPassword.InvisibleChar = '●';
            this.fixed1.Add(this.txtPassword);
            Gtk.Fixed.FixedChild w14 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.txtPassword]));
            w14.X = 215;
            w14.Y = 210;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("Add users");
            this.fixed1.Add(this.label10);
            Gtk.Fixed.FixedChild w15 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label10]));
            w15.X = 21;
            w15.Y = 340;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.btnUsers = new Gtk.Button();
            this.btnUsers.CanFocus = true;
            this.btnUsers.Name = "btnUsers";
            this.btnUsers.UseUnderline = true;
            // Container child btnUsers.Gtk.Container+ContainerChild
            Gtk.Alignment w16 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            w16.Name = "GtkAlignment";
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w17 = new Gtk.HBox();
            w17.Name = "GtkHBox";
            w17.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w18 = new Gtk.Image();
            w18.Name = "image4";
            w18.Pixbuf = Gdk.Pixbuf.LoadFromResource("users.png");
            w17.Add(w18);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w20 = new Gtk.Label();
            w20.Name = "GtkLabel";
            w20.LabelProp = "";
            w17.Add(w20);
            w16.Add(w17);
            this.btnUsers.Add(w16);
            this.fixed1.Add(this.btnUsers);
            Gtk.Fixed.FixedChild w24 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.btnUsers]));
            w24.X = 28;
            w24.Y = 277;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.WidthRequest = 370;
            this.hseparator2.Name = "hseparator2";
            this.fixed1.Add(this.hseparator2);
            Gtk.Fixed.FixedChild w25 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator2]));
            w25.X = 12;
            w25.Y = 251;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.txtFileUsers = new Gtk.Entry();
            this.txtFileUsers.CanFocus = true;
            this.txtFileUsers.Name = "txtFileUsers";
            this.txtFileUsers.IsEditable = true;
            this.txtFileUsers.InvisibleChar = '●';
            this.fixed1.Add(this.txtFileUsers);
            Gtk.Fixed.FixedChild w26 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.txtFileUsers]));
            w26.X = 215;
            w26.Y = 295;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("File");
            this.fixed1.Add(this.label9);
            Gtk.Fixed.FixedChild w27 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label9]));
            w27.X = 133;
            w27.Y = 300;
            w1.Add(this.fixed1);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(w1[this.fixed1]));
            w28.Position = 0;
            w28.Expand = false;
            w28.Fill = false;
            // Internal child tryServer.frmSettings.ActionArea
            Gtk.HButtonBox w29 = this.ActionArea;
            w29.Events = ((Gdk.EventMask)(256));
            w29.Name = "tryServer.frmSettings_ActionArea";
            w29.Spacing = 6;
            w29.BorderWidth = ((uint)(5));
            w29.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child tryServer.frmSettings_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.Ok = new Gtk.Button();
            this.Ok.CanDefault = true;
            this.Ok.CanFocus = true;
            this.Ok.Name = "Ok";
            this.Ok.UseUnderline = true;
            this.Ok.Label = Mono.Unix.Catalog.GetString("Ok");
            this.AddActionWidget(this.Ok, 0);
            Gtk.ButtonBox.ButtonBoxChild w30 = ((Gtk.ButtonBox.ButtonBoxChild)(w29[this.Ok]));
            w30.Expand = false;
            w30.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 421;
            this.DefaultHeight = 479;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.btnUsers.Clicked += new System.EventHandler(this.OnBtnUsersClicked);
            this.Ok.Clicked += new System.EventHandler(this.OnButton30Clicked);
        }
    }
}
