// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace tryServer {
    
    
    public partial class frmUsers {
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Entry lblFile;
        
        private Gtk.Entry txtUser;
        
        private Gtk.Image image107;
        
        private Gtk.Entry lblServer;
        
        private Gtk.Label label4;
        
        private Gtk.Entry txtPassword;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Button btnCancel;
        
        private Gtk.Button btnOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget tryServer.frmUsers
            this.Name = "tryServer.frmUsers";
            this.Title = Mono.Unix.Catalog.GetString("Users");
            this.Modal = true;
            this.DestroyWithParent = true;
            // Container child tryServer.frmUsers.Gtk.Container+ContainerChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Instance");
            this.fixed1.Add(this.label1);
            Gtk.Fixed.FixedChild w1 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
            w1.X = 210;
            w1.Y = 30;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("File");
            this.fixed1.Add(this.label2);
            Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
            w2.X = 210;
            w2.Y = 70;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("User");
            this.fixed1.Add(this.label3);
            Gtk.Fixed.FixedChild w3 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
            w3.X = 210;
            w3.Y = 130;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.lblFile = new Gtk.Entry();
            this.lblFile.CanFocus = true;
            this.lblFile.Name = "lblFile";
            this.lblFile.IsEditable = false;
            this.lblFile.InvisibleChar = '●';
            this.fixed1.Add(this.lblFile);
            Gtk.Fixed.FixedChild w4 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.lblFile]));
            w4.X = 300;
            w4.Y = 65;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.txtUser = new Gtk.Entry();
            this.txtUser.CanFocus = true;
            this.txtUser.Name = "txtUser";
            this.txtUser.IsEditable = true;
            this.txtUser.InvisibleChar = '●';
            this.fixed1.Add(this.txtUser);
            Gtk.Fixed.FixedChild w5 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.txtUser]));
            w5.X = 300;
            w5.Y = 125;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.image107 = new Gtk.Image();
            this.image107.Name = "image107";
            this.image107.Pixbuf = Gdk.Pixbuf.LoadFromResource("User.png");
            this.fixed1.Add(this.image107);
            Gtk.Fixed.FixedChild w6 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.image107]));
            w6.X = 4;
            w6.Y = 32;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.lblServer = new Gtk.Entry();
            this.lblServer.CanFocus = true;
            this.lblServer.Name = "lblServer";
            this.lblServer.IsEditable = false;
            this.lblServer.InvisibleChar = '●';
            this.fixed1.Add(this.lblServer);
            Gtk.Fixed.FixedChild w7 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.lblServer]));
            w7.X = 300;
            w7.Y = 25;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Password");
            this.fixed1.Add(this.label4);
            Gtk.Fixed.FixedChild w8 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
            w8.X = 210;
            w8.Y = 170;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.txtPassword = new Gtk.Entry();
            this.txtPassword.CanFocus = true;
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.IsEditable = true;
            this.txtPassword.Visibility = false;
            this.txtPassword.InvisibleChar = '●';
            this.fixed1.Add(this.txtPassword);
            Gtk.Fixed.FixedChild w9 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.txtPassword]));
            w9.X = 300;
            w9.Y = 165;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.WidthRequest = 300;
            this.hseparator1.Name = "hseparator1";
            this.fixed1.Add(this.hseparator1);
            Gtk.Fixed.FixedChild w10 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator1]));
            w10.X = 184;
            w10.Y = 102;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.btnCancel = new Gtk.Button();
            this.btnCancel.WidthRequest = 80;
            this.btnCancel.CanFocus = true;
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.UseUnderline = true;
            this.btnCancel.Label = Mono.Unix.Catalog.GetString("Cancel");
            this.fixed1.Add(this.btnCancel);
            Gtk.Fixed.FixedChild w11 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.btnCancel]));
            w11.X = 378;
            w11.Y = 244;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.btnOk = new Gtk.Button();
            this.btnOk.WidthRequest = 80;
            this.btnOk.CanFocus = true;
            this.btnOk.Name = "btnOk";
            this.btnOk.UseUnderline = true;
            this.btnOk.Label = Mono.Unix.Catalog.GetString("Ok");
            this.fixed1.Add(this.btnOk);
            Gtk.Fixed.FixedChild w12 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.btnOk]));
            w12.X = 270;
            w12.Y = 245;
            this.Add(this.fixed1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 506;
            this.DefaultHeight = 344;
            this.Show();
            this.btnCancel.Clicked += new System.EventHandler(this.OnBtnCancelClicked);
            this.btnOk.Clicked += new System.EventHandler(this.OnBtnOkClicked);
        }
    }
}
